# Generated by Django 3.1.2 on 2020-11-02 12:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('django_kapnoc', '0002_auto_20201101_1732'),
        ('gallery', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='galleryentry',
            name='image',
        ),
        migrations.AddField(
            model_name='galleryentry',
            name='image',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='django_kapnoc.image'),
            preserve_default=False,
        ),
    ]
