# Generated by Django 3.1.2 on 2020-11-02 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0002_auto_20201102_1209'),
    ]

    operations = [
        migrations.AddField(
            model_name='galleryentry',
            name='description',
            field=models.TextField(default=''),
        ),
    ]
