# Generated by Django 3.1.2 on 2020-11-02 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0003_galleryentry_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='galleryentry',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
    ]
