# Generated by Django 3.1.2 on 2020-11-02 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0004_auto_20201102_1614'),
    ]

    operations = [
        migrations.AddField(
            model_name='galleryentry',
            name='description_en',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='galleryentry',
            name='description_fi',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='galleryentry',
            name='description_fr',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='galleryentry',
            name='description_sv',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='galleryentry',
            name='label_en',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='galleryentry',
            name='label_fi',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='galleryentry',
            name='label_fr',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='galleryentry',
            name='label_sv',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
