# Generated by Django 3.1.2 on 2020-11-09 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0005_auto_20201102_1950'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='galleryentry',
            name='label',
        ),
        migrations.RemoveField(
            model_name='galleryentry',
            name='label_en',
        ),
        migrations.RemoveField(
            model_name='galleryentry',
            name='label_fi',
        ),
        migrations.RemoveField(
            model_name='galleryentry',
            name='label_fr',
        ),
        migrations.RemoveField(
            model_name='galleryentry',
            name='label_sv',
        ),
        migrations.AddField(
            model_name='galleryentry',
            name='name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='galleryentry',
            name='name_en',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='galleryentry',
            name='name_fi',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='galleryentry',
            name='name_fr',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='galleryentry',
            name='name_sv',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
    ]
