# Generated by Django 3.1.2 on 2020-11-05 11:50

from django.db import migrations, models
import martor.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('django_kapnoc', '0002_auto_20201101_1732'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('title_en', models.CharField(max_length=255, null=True)),
                ('title_fr', models.CharField(max_length=255, null=True)),
                ('title_fi', models.CharField(max_length=255, null=True)),
                ('title_sv', models.CharField(max_length=255, null=True)),
                ('body', martor.models.MartorField()),
                ('body_en', martor.models.MartorField(null=True)),
                ('body_fr', martor.models.MartorField(null=True)),
                ('body_fi', martor.models.MartorField(null=True)),
                ('body_sv', martor.models.MartorField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField()),
                ('tags', models.ManyToManyField(to='django_kapnoc.Tag')),
            ],
        ),
    ]
