# Generated by Django 3.1.2 on 2020-11-05 13:04

from django.db import migrations, models
import martor.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('kapno_cc', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='KitchenPage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('title_en', models.CharField(max_length=255, null=True)),
                ('title_fr', models.CharField(max_length=255, null=True)),
                ('title_fi', models.CharField(max_length=255, null=True)),
                ('title_sv', models.CharField(max_length=255, null=True)),
                ('body', martor.models.MartorField()),
                ('body_en', martor.models.MartorField(null=True)),
                ('body_fr', martor.models.MartorField(null=True)),
                ('body_fi', martor.models.MartorField(null=True)),
                ('body_sv', martor.models.MartorField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField()),
                ('description', models.TextField()),
                ('description_en', models.TextField(null=True)),
                ('description_fr', models.TextField(null=True)),
                ('description_fi', models.TextField(null=True)),
                ('description_sv', models.TextField(null=True)),
                ('tags', models.ManyToManyField(to='kapno_cc.Tag')),
            ],
        ),
        migrations.CreateModel(
            name='BlogPage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('title_en', models.CharField(max_length=255, null=True)),
                ('title_fr', models.CharField(max_length=255, null=True)),
                ('title_fi', models.CharField(max_length=255, null=True)),
                ('title_sv', models.CharField(max_length=255, null=True)),
                ('body', martor.models.MartorField()),
                ('body_en', martor.models.MartorField(null=True)),
                ('body_fr', martor.models.MartorField(null=True)),
                ('body_fi', martor.models.MartorField(null=True)),
                ('body_sv', martor.models.MartorField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField()),
                ('description', models.TextField()),
                ('description_en', models.TextField(null=True)),
                ('description_fr', models.TextField(null=True)),
                ('description_fi', models.TextField(null=True)),
                ('description_sv', models.TextField(null=True)),
                ('tags', models.ManyToManyField(to='kapno_cc.Tag')),
            ],
        ),
    ]
