# Generated by Django 3.1.2 on 2020-11-05 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpage',
            name='description',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='blogpage',
            name='description_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='blogpage',
            name='description_fi',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='blogpage',
            name='description_fr',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='blogpage',
            name='description_sv',
            field=models.TextField(null=True),
        ),
    ]
