# Generated by Django 3.1.2 on 2020-11-05 12:45

from django.db import migrations, models
import martor.models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_kitchenpage'),
    ]

    operations = [
        migrations.AddField(
            model_name='kitchenpage',
            name='body_en',
            field=martor.models.MartorField(null=True),
        ),
        migrations.AddField(
            model_name='kitchenpage',
            name='body_fi',
            field=martor.models.MartorField(null=True),
        ),
        migrations.AddField(
            model_name='kitchenpage',
            name='body_fr',
            field=martor.models.MartorField(null=True),
        ),
        migrations.AddField(
            model_name='kitchenpage',
            name='body_sv',
            field=martor.models.MartorField(null=True),
        ),
        migrations.AddField(
            model_name='kitchenpage',
            name='description_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='kitchenpage',
            name='description_fi',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='kitchenpage',
            name='description_fr',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='kitchenpage',
            name='description_sv',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='kitchenpage',
            name='title_en',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='kitchenpage',
            name='title_fi',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='kitchenpage',
            name='title_fr',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='kitchenpage',
            name='title_sv',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
