# Generated by Django 3.1.4 on 2021-02-26 17:37

from django.db import migrations, models
import martor.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('utils', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomePage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('body', martor.models.MartorField()),
                ('body_en', martor.models.MartorField(null=True)),
                ('body_fr', martor.models.MartorField(null=True)),
                ('body_fi', martor.models.MartorField(null=True)),
                ('body_sv', martor.models.MartorField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField()),
                ('tags', models.ManyToManyField(to='utils.Tag')),
            ],
        ),
    ]
