# Generated by Django 3.1.2 on 2020-11-03 18:39

from django.db import migrations
import martor.models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='body_en',
            field=martor.models.MartorField(null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='body_fi',
            field=martor.models.MartorField(null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='body_fr',
            field=martor.models.MartorField(null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='body_sv',
            field=martor.models.MartorField(null=True),
        ),
    ]
