# Generated by Django 3.1.2 on 2020-11-05 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20201105_1316'),
        ('home', '0002_auto_20201103_1839'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='tags',
            field=models.ManyToManyField(to='blog.Tag'),
        ),
    ]
